import streamlit as st
import requests
import asyncio
import aiohttp
from qdrant_client import QdrantClient
from sentence_transformers import SentenceTransformer

# --- Page Config ---
st.set_page_config(
    page_title="NotionAtlas",
    page_icon="🧭",
    layout="wide"
)

# --- Title with Inline GitHub Icon ---
st.markdown(
    """
    <div style="display:flex; justify-content:center; align-items:center; gap:10px; padding: 20px 0;">
        <h1 style="margin-bottom:0;">🧭 NotionAtlas</h1>
    </div>
    <h3 style="text-align:center; color: gray; font-weight: 400; margin-top: 0;">
        Turn your Notion workspace into an intelligent, searchable knowledge hub.
    </h3>
    """,
    unsafe_allow_html=True
)

# --- Example Queries Section ---
st.markdown(
    """
    <style>
    .example-queries {
        background: white;
        border-radius: 12px;
        padding: 15px 25px;
        margin: 15px auto 30px auto;
        max-width: 500px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
        font-size: 0.95em;
        color: #333;
        text-align: center;
    }
    </style>
    <div class="example-queries">
        💡 <b>Try asking:</b><br>
        • "Summarize my MongoDB exam prep notes"<br>
        • "What did I learn in Week 3: Sequence Models?"<br>
        • "Show me all tasks marked as 'Not Started'"
    </div>
    """,
    unsafe_allow_html=True
)

# --- Load Secrets ---
LLAMA_API_URL = "https://api.llama.com/v1/chat/completions"
LLAMA_API_KEY = st.secrets["LLAMA_API_KEY"]
QDRANT_URL = st.secrets["QDRANT_URL"]
QDRANT_API_KEY = st.secrets["QDRANT_API_KEY"]
HF_TOKEN = st.secrets.get("HF_TOKEN", None)

COLLECTION_NAME = "notion_content"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"

# --- Initialize Clients ---
qdrant = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
embedder = SentenceTransformer(EMBEDDING_MODEL, use_auth_token=HF_TOKEN)

# --- Session State ---
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "conversation_context" not in st.session_state:
    st.session_state.conversation_context = ""


# --- Async Chat Function ---
async def chat_with_memory(user_input: str):
    # 1️⃣ Encode query
    vector = embedder.encode(user_input).tolist()
    
    # 2️⃣ Query Qdrant
    results = qdrant.query_points(
        collection_name=COLLECTION_NAME,
        query=vector,
        limit=5
    )

    # 3️⃣ Prepare semantic context
    context = "\n".join([
        hit.payload.get('chunk_text', '') for hit in results.points
    ]) or "No relevant context found."

    # 4️⃣ Update conversation memory
    st.session_state.conversation_context += f"\nUser: {user_input}"
    combined_context = (
        f"Conversation history:\n{st.session_state.conversation_context}\n\n"
        f"Relevant Notion context:\n{context}"
    )

    # 5️⃣ Call LLAMA API
    payload = {
        "model": "Llama-4-Maverick-17B-128E-Instruct-FP8",
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are NotionAtlas, an AI assistant for Notion workspace queries. "
                    "Use the context if available. If context is insufficient, "
                    "start with: 'Note: This answer is **generated by LLAMA** "
                    "& falls **outside the scope of the Notion workspace data.**'"
                )
            },
            {"role": "user", "content": combined_context}
        ],
        "max_tokens": 500,
        "temperature": 0.2
    }

    headers = {"Authorization": f"Bearer {LLAMA_API_KEY}", "Content-Type": "application/json"}

    async with aiohttp.ClientSession() as session:
        async with session.post(LLAMA_API_URL, json=payload, headers=headers) as resp:
            if resp.status == 200:
                data = await resp.json()
                answer = data["completion_message"]["content"]["text"].strip()
            else:
                answer = f"Error: {await resp.text()}"

    # 6️⃣ Save to chat history and memory
    st.session_state.chat_history.append({"role": "user", "content": user_input})
    st.session_state.chat_history.append({"role": "assistant", "content": answer})
    st.session_state.conversation_context += f"\nAssistant: {answer}"

    return answer


# --- Chat Input ---
user_input = st.chat_input("Ask a question about your Notion workspace...")

if user_input:
    with st.spinner("Thinking..."):
        asyncio.run(chat_with_memory(user_input))

# --- Display Chat History ---
for msg in st.session_state.chat_history:
    if msg["role"] == "user":
        st.chat_message("user").markdown(msg["content"])
    else:
        st.chat_message("assistant").markdown(msg["content"])
